services:
  db:
    image: mariadb:10.11.15
    container_name: mariadb_lokal
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_docker
    links:
      - db
    ports:
      - "8080:80" # Akses di browser lewat localhost:8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306